name: Bearer Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Bearer security scan
        uses: bearer/bearer-action@v2
        with:
          args: scan --format json --output bearer-report.json 